package com.vk.repository.microservice;

import com.vk.entity.device.DeviceModelSecondCehBalonTRM138;
import com.vk.entity.json.JsonBodyListForTableModelSecondCehBalonTRM138;
import com.vk.entity.table.TableModelSecondCehBalonTRM138;

public interface RepositoryMicroserviceSecondCehBalonRaspberry extends RepositoryMicroserviceRoot<TableModelSecondCehBalonTRM138, JsonBodyListForTableModelSecondCehBalonTRM138, DeviceModelSecondCehBalonTRM138> {
}
