package com.vk.repository.microservice;

import com.vk.entity.device.DeviceModelSecondCehBalonTRM138;
import com.vk.entity.device.DeviceModelSiliconCameraVulkanTRM251;
import com.vk.entity.json.JsonBodyListForTableModelSecondCehBalonTRM138;
import com.vk.entity.json.JsonBodyListForTableModelSiliconCameraVulkanTRM251;
import com.vk.entity.table.TableModelSecondCehBalonTRM138;
import com.vk.entity.table.TableModelSiliconeCameraVulcanTRM251;

public interface RepositoryMicroserviceSiliconCameraVulcanRaspberry extends RepositoryMicroserviceRoot<TableModelSiliconeCameraVulcanTRM251, JsonBodyListForTableModelSiliconCameraVulkanTRM251, DeviceModelSiliconCameraVulkanTRM251> {
}
