package com.vk.repository.modbus;

import com.vk.entity.device.DeviceModelSecondCehKameraVulcan2MPR51;

/**
 * Created by KIP-PC99 on 21.11.2018.
 */
public interface ModbusRepositorySecondCehKameraVulcan2MPR51 extends RootModbusRepository<DeviceModelSecondCehKameraVulcan2MPR51>{

    void readDataFromRegister0(final boolean enableBatch);
    void readDataFromRegister1(final boolean enableBatch);
    void readDataFromRegister2(final boolean enableBatch);
    void readDataFromRegister3(final boolean enableBatch);
    void readDataFromRegister4(final boolean enableBatch);
    void readDataFromRegister5(final boolean enableBatch);
    void readDataFromRegister6(final boolean enableBatch);
    void readDataFromRegister7(final boolean enableBatch);
    void readDataFromRegister8(final boolean enableBatch);
    void readDataFromRegister9(final boolean enableBatch);
    void readDataFromRegister10(final boolean enableBatch);
    void readDataFromRegister11(final boolean enableBatch);
    void readDataFromRegister12(final boolean enableBatch);
    void readDataFromRegister13(final boolean enableBatch);
    void readDataFromRegister14(final boolean enableBatch);
    void readDataFromRegister15(final boolean enableBatch);
    void readDataFromRegister16(final boolean enableBatch);
    void readDataFromRegister17(final boolean enableBatch);
    void readDataFromRegister18(final boolean enableBatch);
    void readDataFromRegister19(final boolean enableBatch);
    void readDataFromRegister20(final boolean enableBatch);
    void readDataFromRegister21(final boolean enableBatch);
    void readDataFromRegister22(final boolean enableBatch);
    void readDataFromRegister23(final boolean enableBatch);
    void readDataFromRegister24(final boolean enableBatch);
    void readDataFromRegister25(final boolean enableBatch);
    void readDataFromRegister26(final boolean enableBatch);
    void readDataFromRegister27(final boolean enableBatch);
    void readDataFromRegister28(final boolean enableBatch);
    void readDataFromRegister29(final boolean enableBatch);
    void readDataFromRegister30(final boolean enableBatch);
    void readDataFromRegister31(final boolean enableBatch);
    void readDataFromRegister32(final boolean enableBatch);
    void readDataFromRegister33(final boolean enableBatch);
    void readDataFromRegister34(final boolean enableBatch);
    void readDataFromRegister35(final boolean enableBatch);
    void readDataFromRegister36(final boolean enableBatch);
    void readDataFromRegister37(final boolean enableBatch);
    void readDataFromRegister38(final boolean enableBatch);
    void readDataFromRegister39(final boolean enableBatch);
    void readDataFromRegister40(final boolean enableBatch);
    void readDataFromRegister41(final boolean enableBatch);
    void readDataFromRegister42(final boolean enableBatch);
    void readDataFromRegister43(final boolean enableBatch);
    void readDataFromRegister44(final boolean enableBatch);
    void readDataFromRegister45(final boolean enableBatch);
    void readDataFromRegister46(final boolean enableBatch);

    void writeDataToRegister0(final float value);
    void writeDataToRegister1(final float value);
    void writeDataToRegister2(final float value);
    void writeDataToRegister3(final float value);
    void writeDataToRegister4(final float value);
    void writeDataToRegister5(final float value);
    void writeDataToRegister6(final float value);
    void writeDataToRegister7(final float value);
    void writeDataToRegister8(final float value);
    void writeDataToRegister9(final short value);
    void writeDataToRegister10(final float value);
    void writeDataToRegister11(final float value);
    void writeDataToRegister12(final short value);
    void writeDataToRegister13(final float value);
    void writeDataToRegister14(final float value);
    void writeDataToRegister15(final short value);
    void writeDataToRegister16(final float value);
    void writeDataToRegister17(final float value);
    void writeDataToRegister18(final short value);
    void writeDataToRegister19(final float value);
    void writeDataToRegister20(final float value);
    void writeDataToRegister21(final short value);
    void writeDataToRegister22(final float value);
    void writeDataToRegister23(final float value);
    void writeDataToRegister24(final short value);
    void writeDataToRegister25(final float value);
    void writeDataToRegister26(final float value);
    void writeDataToRegister27(final short value);
    void writeDataToRegister28(final float value);
    void writeDataToRegister29(final float value);
    void writeDataToRegister30(final short value);
    void writeDataToRegister31(final float value);
    void writeDataToRegister32(final float value);
    void writeDataToRegister33(final short value);
    void writeDataToRegister34(final float value);
    void writeDataToRegister35(final float value);
    void writeDataToRegister36(final short value);
    void writeDataToRegister37(final float value);
    void writeDataToRegister38(final float value);
    void writeDataToRegister39(final short value);
    void writeDataToRegister40(final float value);
    void writeDataToRegister41(final float value);
    void writeDataToRegister42(final short value);
    void writeDataToRegister43(final float value);
    void writeDataToRegister44(final float value);
    void writeDataToRegister45(final short value);
    void writeDataToRegister46(final short value);
}
