package com.vk.repository.modbus;

import com.vk.entity.device.DeviceModelSecondCehKameraVulcan1MPR51;
import com.vk.entity.device.DeviceModelSecondCehKameraVulcan3MPR51;

/**
 * Created by KIP-PC99 on 21.11.2018.
 */
public interface ModbusRepositorySecondCehKameraVulcan3MPR51 extends RootModbusRepository<DeviceModelSecondCehKameraVulcan3MPR51>{

    public void readDataFromRegister0(final boolean enableBatch);
    public void readDataFromRegister1(final boolean enableBatch);
    public void readDataFromRegister2(final boolean enableBatch);
    public void readDataFromRegister3(final boolean enableBatch);
    public void readDataFromRegister4(final boolean enableBatch);
    public void readDataFromRegister5(final boolean enableBatch);
    public void readDataFromRegister6(final boolean enableBatch);
    public void readDataFromRegister7(final boolean enableBatch);
    public void readDataFromRegister8(final boolean enableBatch);
    public void readDataFromRegister9(final boolean enableBatch);
    public void readDataFromRegister10(final boolean enableBatch);
    public void readDataFromRegister11(final boolean enableBatch);
    public void readDataFromRegister12(final boolean enableBatch);
    public void readDataFromRegister13(final boolean enableBatch);
    public void readDataFromRegister14(final boolean enableBatch);
    public void readDataFromRegister15(final boolean enableBatch);
    public void readDataFromRegister16(final boolean enableBatch);
    public void readDataFromRegister17(final boolean enableBatch);
    public void readDataFromRegister18(final boolean enableBatch);
    public void readDataFromRegister19(final boolean enableBatch);
    public void readDataFromRegister20(final boolean enableBatch);
    public void readDataFromRegister21(final boolean enableBatch);
    public void readDataFromRegister22(final boolean enableBatch);
    public void readDataFromRegister23(final boolean enableBatch);
    public void readDataFromRegister24(final boolean enableBatch);
    public void readDataFromRegister25(final boolean enableBatch);
    public void readDataFromRegister26(final boolean enableBatch);
    public void readDataFromRegister27(final boolean enableBatch);
    public void readDataFromRegister28(final boolean enableBatch);
    public void readDataFromRegister29(final boolean enableBatch);
    public void readDataFromRegister30(final boolean enableBatch);
    public void readDataFromRegister31(final boolean enableBatch);
    public void readDataFromRegister32(final boolean enableBatch);
    public void readDataFromRegister33(final boolean enableBatch);
    public void readDataFromRegister34(final boolean enableBatch);
    public void readDataFromRegister35(final boolean enableBatch);
    public void readDataFromRegister36(final boolean enableBatch);
    public void readDataFromRegister37(final boolean enableBatch);
    public void readDataFromRegister38(final boolean enableBatch);
    public void readDataFromRegister39(final boolean enableBatch);
    public void readDataFromRegister40(final boolean enableBatch);
    public void readDataFromRegister41(final boolean enableBatch);
    public void readDataFromRegister42(final boolean enableBatch);
    public void readDataFromRegister43(final boolean enableBatch);
    public void readDataFromRegister44(final boolean enableBatch);
    public void readDataFromRegister45(final boolean enableBatch);
    public void readDataFromRegister46(final boolean enableBatch);

    public void writeDataToRegister0(final float value);
    public void writeDataToRegister1(final float value);
    public void writeDataToRegister2(final float value);
    public void writeDataToRegister3(final float value);
    public void writeDataToRegister4(final float value);
    public void writeDataToRegister5(final float value);
    public void writeDataToRegister6(final float value);
    public void writeDataToRegister7(final float value);
    public void writeDataToRegister8(final float value);
    public void writeDataToRegister9(final int value);
    public void writeDataToRegister10(final float value);
    public void writeDataToRegister11(final float value);
    public void writeDataToRegister12(final int value);
    public void writeDataToRegister13(final float value);
    public void writeDataToRegister14(final float value);
    public void writeDataToRegister15(final int value);
    public void writeDataToRegister16(final float value);
    public void writeDataToRegister17(final float value);
    public void writeDataToRegister18(final int value);
    public void writeDataToRegister19(final float value);
    public void writeDataToRegister20(final float value);
    public void writeDataToRegister21(final int value);
    public void writeDataToRegister22(final float value);
    public void writeDataToRegister23(final float value);
    public void writeDataToRegister24(final int value);
    public void writeDataToRegister25(final float value);
    public void writeDataToRegister26(final float value);
    public void writeDataToRegister27(final int value);
    public void writeDataToRegister28(final float value);
    public void writeDataToRegister29(final float value);
    public void writeDataToRegister30(final int value);
    public void writeDataToRegister31(final float value);
    public void writeDataToRegister32(final float value);
    public void writeDataToRegister33(final int value);
    public void writeDataToRegister34(final float value);
    public void writeDataToRegister35(final float value);
    public void writeDataToRegister36(final int value);
    public void writeDataToRegister37(final float value);
    public void writeDataToRegister38(final float value);
    public void writeDataToRegister39(final int value);
    public void writeDataToRegister40(final float value);
    public void writeDataToRegister41(final float value);
    public void writeDataToRegister42(final int value);
    public void writeDataToRegister43(final float value);
    public void writeDataToRegister44(final float value);
    public void writeDataToRegister45(final float value);
    public void writeDataToRegister46(final int value);
}
